name: Docker Actions

on:
  push:
    branches:
      - dev

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: dbt-run
        id: dbt-run
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt docs generate --profiles-dir ."
          dbt_project_folder: "dbt_project"
        env:
          DBT_BIGQUERY_TOKEN: ${{ secrets.DBT_BIGQUERY_TOKEN }}
      - name: Get the result
        run: echo "${{ steps.dbt-run.outputs.result }}"
        shell: bash
      - id: upload-file
        uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
        with:
          credentials: ${{ secrets.DBT_BIGQUERY_TOKEN }}
          path: ./target
          destination: analytics-buddy-internal-docs

      - name: SendGrid
        uses: peter-evans/sendgrid-action@v1
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SENDGRID_FROM: ${{ secrets.SENDGRID_FROM }}
          SENDGRID_TO: ${{ secrets.SENDGRID_TO }}
